# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'robo.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import pyttsx3
#Created by @Omkar Kanse
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1213, 845)
        MainWindow.setStyleSheet("background-color: rgb(0, 0, 0);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")#Created by @Omkar Kanse
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(410, 30, 391, 71))
        self.label.setStyleSheet("color: rgb(255, 255, 255);\n"
"font: 75 36pt \"MS Shell Dlg 2\";\n"
"border-color: rgb(0, 255, 255);")
        self.label.setObjectName("label")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(270, 540, 671, 51))
        self.lineEdit.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.lineEdit.setObjectName("lineEdit")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(280, 670, 661, 61))
        self.label_3.setStyleSheet("font: 75 18pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")#Created by @Omkar Kanse
        self.label_3.setText("")
        self.label_3.setObjectName("label_3")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(310, 110, 591, 421))
        self.label_2.setStyleSheet("image: url(:/roco/logo.png);")
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(520, 610, 141, 28))
        self.pushButton.setStyleSheet("color: rgb(0, 0, 0);\n"
"font: 75 10pt \"MS Shell Dlg 2\";\n"
"background-color: rgb(85, 255, 255);")#Created by @Omkar Kanse
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.pushButton.clicked.connect(self.robo_speaker)

    def robo_speaker(self):
        engine = pyttsx3.init()
        #Welcome to RoboSpeaker 1.1
        # Created by @Omkar Kanse
        while True:
            x1 = self.lineEdit.text()
            #x1 = input("Enter what you want me to speak (or 'exit' to quit): ")
            if x1 == 'bye':
                engine.say("Bye bye my good friend")
                engine.runAndWait()#Created by @Omkar Kanse
                break
            engine.say(x1)#Created by @Omkar Kanse
            engine.runAndWait()
            self.label_3.setText(x1)#Created by @Omkar Kanse
            self.lineEdit.clear()
            break



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Robo-Speaker"))
        self.label.setText(_translate("MainWindow", "Robo-Speaker"))#Created by @Omkar Kanse
        self.label_2.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "Enter"))
import roco_rc

#Created by @Omkar Kanse
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
#Created by @Omkar Kanse